site_name: SDKBOX
pages:
- Overview: 'index.md'
- Cocos2d-x:
    - 'Overview': 'cocos.md'
    - 'CLI Installer': 'installer.md'
    - 'For Cocos Creator': 'qa/cocos_creator.md'
    - Plugins:
        - 'Achievements': 'plugins/achievement/index.md'
        - '_Achievements':
            - 'Cocos2d-x v3.x':
                - 'Achievements with C++': 'plugins/achievement/v3-cpp.md'
                - 'Achievements with Javascript': 'plugins/achievement/v3-js.md'
                - 'Achievements with Lua': 'plugins/achievement/v3-lua.md'
        - 'AdColony': 'plugins/adcolony/index.md'
        - '_AdColony':
            - 'Cocos2d-x v3.x':
                - 'AdColony with C++': 'plugins/adcolony/v3-cpp.md'
                - 'AdColony with JS': 'plugins/adcolony/v3-js.md'
                - 'AdColony with Lua': 'plugins/adcolony/v3-lua.md'
        - 'AdMob': 'plugins/admob/index.md'
        - '_AdMob':
            - 'Cocos2d-x v3.x':
                - 'AdMob with C++': 'plugins/admob/v3-cpp.md'
                - 'AdMob with Javascript': 'plugins/admob/v3-js.md'
                - 'AdMob with Lua': 'plugins/admob/v3-lua.md'
        - 'AgeCheq': 'plugins/agecheq/index.md'
        - '_AgeCheq':
            - 'Cocos2d-x v3.x':
                - 'AgeCheq with C++': 'plugins/agecheq/v3-cpp.md'
                - 'AgeCheq with Javascript': 'plugins/agecheq/v3-js.md'
                - 'AgeCheq with Lua': 'plugins/agecheq/v3-lua.md'
        - 'Appnext': 'plugins/appnext/index.md'
        - '_Appnext':
            - 'Cocos2d-x v3.x':
                - 'Appnext with C++': 'plugins/appnext/v3-cpp.md'
                - 'Appnext with Javascript': 'plugins/appnext/v3-js.md'
                - 'Appnext with Lua': 'plugins/appnext/v3-lua.md'
        - 'Appodeal': 'plugins/appodeal/index.md'
        - '_Appodeal':
            - 'Cocos2d-x v3.x':
                - 'Appodeal with C++': 'plugins/appodeal/v3-cpp.md'
                - 'Appodeal with Javascript': 'plugins/appodeal/v3-js.md'
                - 'Appodeal with Lua': 'plugins/appodeal/v3-lua.md'
        - 'Amazon': 'plugins/amazon/index.md'
        - '_Amazon':
            - 'Cocos2d-x v3.x':
                - 'Amazon with C++': 'plugins/amazon/v3-cpp.md'
                - 'Amazon with Javascript': 'plugins/amazon/v3-js.md'
                - 'Amazon with Lua': 'plugins/amazon/v3-lua.md'
        - 'Apteligent': 'plugins/apteligent/index.md'
        - '_Apteligent':
            - 'Cocos2d-x v3.x':
                - 'Apteligent with C++': 'plugins/apteligent/v3-cpp.md'
                - 'Apteligent with Javascript': 'plugins/apteligent/v3-js.md'
                - 'Apteligent with Lua': 'plugins/apteligent/v3-lua.md'
        - 'Bee7': 'plugins/bee7/index.md'
        - '_Bee7':
            - 'Cocos2d-x v3.x':
                - 'Bee7 with C++': 'plugins/bee7/v3-cpp.md'
                - 'Bee7 with Javascript': 'plugins/bee7/v3-js.md'
                - 'Bee7 with Lua': 'plugins/bee7/v3-lua.md'
        - 'Chartboost': 'plugins/chartboost/index.md'
        - '_Chartboost':
            - 'Cocos2d-x v3.x':
                - 'Chartboost with C++': 'plugins/chartboost/v3-cpp.md'
                - 'Chartboost with Javascript': 'plugins/chartboost/v3-js.md'
                - 'Chartboost with Lua': 'plugins/chartboost/v3-lua.md'
        - 'EthWallet': 'plugins/ethwallet/index.md'
        - 'Facebook': 'plugins/facebook/index.md'
        - '_Facebook':
            - 'Cocos2d-x v3.x':
                - 'Facebook with C++': 'plugins/facebook/v3-cpp.md'
                - 'Facebook with Javascript': 'plugins/facebook/v3-js.md'
                - 'Facebook with Lua': 'plugins/facebook/v3-lua.md'
        - 'Facebook Gameroom': 'plugins/gameroom/index.md'
        - '_Facebook Gameroom':
            - 'Cocos2d-x v3.x':
                - 'Facebook Gameroom with C++': 'plugins/gameroom/v3-cpp.md'
                - 'Facebook Gameroom with Javascript': 'plugins/gameroom/v3-js.md'
        - 'Firebase': 'plugins/firebase/index.md'
        - '_Firebase':
            - 'Cocos2d-x v3.x':
                - 'Firebase with C++': 'plugins/firebase/v3-cpp.md'
                - 'Firebase with Javascript': 'plugins/firebase/v3-js.md'
                - 'Firebase with Lua': 'plugins/firebase/v3-lua.md'
        - 'Flurry Analytics': 'plugins/flurryanalytics/index.md'
        - '_Flurry Analytics':
            - 'Cocos2d-x v3.x':
                - 'Flurry with C++': 'plugins/flurryanalytics/v3-cpp.md'
                - 'Flurry with Javascript': 'plugins/flurryanalytics/v3-js.md'
                - 'Flurry with Lua': 'plugins/flurryanalytics/v3-lua.md'
        - 'Fyber': 'plugins/fyber/index.md'
        - '_Fyber':
            - 'Cocos2d-x v3.x':
                - 'Fyber with C++': 'plugins/fyber/v3-cpp.md'
                - 'Fyber with Javascript': 'plugins/fyber/v3-js.md'
                - 'Fyber with Lua': 'plugins/fyber/v3-lua.md'
        - 'Google Analytics': 'plugins/googleanalytics/index.md'
        - '_Google Analytics':
            - 'Cocos2d-x v3.x':
                - 'Google Analytics with C++': 'plugins/googleanalytics/v3-cpp.md'
                - 'Google Analytics with Javascript': 'plugins/googleanalytics/v3-js.md'
                - 'Google Analytics with Lua': 'plugins/googleanalytics/v3-lua.md'
        - 'Google Play Games': 'plugins/googleplay/index.md'
        - '_Google Play Games':
            - 'Google Play Services with C++': 'plugins/googleplay/v3-cpp.md'
            - 'Google Play Services with Javascript': 'plugins/googleplay/v3-js.md'
            - 'Google Play Services with Lua': 'plugins/googleplay/v3-lua.md'
        - 'In-App Purchase': 'plugins/iap/index.md'
        - '_IAP':
            - 'Cocos2d-x v3.x':
                - 'In-App Purchases(IAP) with C++': 'plugins/iap/v3-cpp.md'
                - 'In-App Purchases(IAP) with Javascript': 'plugins/iap/v3-js.md'
                - 'In-App Purchases(IAP) with Lua': 'plugins/iap/v3-lua.md'
        - 'InMobi': 'plugins/inmobi/index.md'
        - '_InMobi':
            - 'Cocos2d-x v3.x':
                - 'InMobi with C++': 'plugins/inmobi/v3-cpp.md'
                - 'InMobi with Javascript': 'plugins/inmobi/v3-js.md'
                - 'InMobi with Lua': 'plugins/inmobi/v3-lua.md'
        - 'Kochava': 'plugins/kochava/index.md'
        - '_Kochava':
            - 'Cocos2d-x v3.x':
                - 'Kochava with C++': 'plugins/kochava/v3-cpp.md'
                - 'Kochava with Javascript': 'plugins/kochava/v3-js.md'
                - 'Kochava with Lua': 'plugins/kochava/v3-lua.md'
        - 'LeadBolt': 'plugins/leadbolt/index.md'
        - '_LeadBolt':
            - 'Cocos2d-x v3.x':
                - 'LeadBolt with C++': 'plugins/leadbolt/v3-cpp.md'
                - 'LeadBolt with Javascript': 'plugins/leadbolt/v3-js.md'
                - 'LeadBolt with Lua': 'plugins/leadbolt/v3-lua.md'
        - 'Leaderboard': 'plugins/leaderboard/index.md'
        - '_Leaderboard':
            - 'Cocos2d-x v3.x':
                - 'Leaderboard with C++': 'plugins/leaderboard/v3-cpp.md'
                - 'Leaderboard with Javascript': 'plugins/leaderboard/v3-js.md'
                - 'Leaderboard with Lua': 'plugins/leaderboard/v3-lua.md'
        - 'OneSignal': 'plugins/onesignal/index.md'
        - '_OneSignal':
            - 'Cocos2d-x v3.x':
                - 'OneSignal with C++': 'plugins/onesignal/v3-cpp.md'
                - 'OneSignal with Javascript': 'plugins/onesignal/v3-js.md'
                - 'OneSignal with Lua': 'plugins/onesignal/v3-lua.md'
        - 'Playphone': 'plugins/playphone/index.md'
        - '_Playphone':
            - 'Cocos2d-x v3.x':
                - 'Playphone with C++': 'plugins/playphone/v3-cpp.md'
                - 'Playphone with Javascript': 'plugins/playphone/v3-js.md'
                - 'Playphone with Lua': 'plugins/playphone/v3-lua.md'
        - 'Phunware Ads': 'plugins/phunwareads/index.md'
        - '_Phunware Ads':
            - 'Cocos2d-x v3.x':
                - 'Phunware Ads with C++': 'plugins/phunwareads/v3-cpp.md'
                - 'Phunware Ads with Javascript': 'plugins/phunwareads/v3-js.md'
                - 'Phunware Ads with Lua': 'plugins/phunwareads/v3-lua.md'
        - 'Phunware Messaging': 'plugins/phunwaremessaging/index.md'
        - '_Phunware Messaging':
            - 'Cocos2d-x v3.x':
                - 'Phunware Messaging with C++': 'plugins/phunwaremessaging/v3-cpp.md'
                - 'Phunware Messaging with Javascript': 'plugins/phunwaremessaging/v3-js.md'
                - 'Phunware Messaging with Lua': 'plugins/phunwaremessaging/v3-lua.md'
        - 'Ratings & Reviews': 'plugins/review/index.md'
        - '_Ratings & Reviews':
            - 'Cocos2d-x v3.x':
                - 'App Rating & Review with C++': 'plugins/review/v3-cpp.md'
                - 'App Rating & Review with Javascript': 'plugins/review/v3-js.md'
                - 'App Rating & Review with Lua': 'plugins/review/v3-lua.md'
        - 'SDKBOX Ads': 'plugins/sdkboxads/index.md'
        - '_sdkboxAds':
            - 'Cocos2d-x v3.x':
                - 'Ads with C++': 'plugins/sdkboxads/v3-cpp.md'
                - 'Ads with Javascript': 'plugins/sdkboxads/v3-js.md'
                - 'Ads with Lua': 'plugins/sdkboxads/v3-lua.md'
        - 'SDKBOX Play': 'plugins/sdkboxplay/index.md'
        - '_sdkboxPlay':
            - 'Cocos2d-x v3.x':
                - 'Play with C++': 'plugins/sdkboxplay/v3-cpp.md'
                - 'Play with Javascript': 'plugins/sdkboxplay/v3-js.md'
                - 'Play with Lua': 'plugins/sdkboxplay/v3-lua.md'
        - 'Social Sharing': 'plugins/share/index.md'
        - '_Share':
            - 'Cocos2d-x v3.x':
                - 'Share with C++': 'plugins/share/v3-cpp.md'
                - 'Share with Javascript': 'plugins/share/v3-js.md'
                - 'Share with Lua': 'plugins/share/v3-lua.md'
        - 'Tapcore': 'plugins/tapcore/index.md'
        - '_Tapcore':
            - 'Cocos2d-x v3.x':
                - 'Share with C++': 'plugins/tapcore/v3-cpp.md'
                - 'Share with Javascript': 'plugins/tapcore/v3-js.md'
                - 'Share with Lua': 'plugins/tapcore/v3-lua.md'
        - 'Tune': 'plugins/tune/index.md'
        - '_Tune':
            - 'Cocos2d-x v3.x':
                - 'Tune with C++': 'plugins/tune/v3-cpp.md'
                - 'Tune with Javascript': 'plugins/tune/v3-js.md'
                - 'Tune with Lua': 'plugins/tune/v3-lua.md'
        - 'UnityAds': 'plugins/unityads/index.md'
        - '_UnityAds':
            - 'Cocos2d-x v3.x':
                - 'UnityAds with C++': 'plugins/unityads/v3-cpp.md'
                - 'UnityAds with Javascript': 'plugins/unityads/v3-js.md'
                - 'UnityAds with Lua': 'plugins/unityads/v3-lua.md'
        - 'Valuepotion': 'plugins/valuepotion/index.md'
        - '_Valuepotion':
            - 'Cocos2d-x v3.x':
                - 'Valuepotion with C++': 'plugins/valuepotion/v3-cpp.md'
                - 'Valuepotion with Javascript': 'plugins/valuepotion/v3-js.md'
                - 'Valuepotion with Lua': 'plugins/valuepotion/v3-lua.md'
        - 'Vungle': 'plugins/vungle/index.md'
        - '_Vungle':
            - 'Cocos2d-x v3.x':
                - 'Vungle with C++': 'plugins/vungle/v3-cpp.md'
                - 'Vungle with Javascript': 'plugins/vungle/v3-js.md'
                - 'Vungle with Lua': 'plugins/vungle/v3-lua.md'
        - 'Youtube': 'plugins/youtube/index.md'
        - '_Youtube':
            - 'Cocos2d-x v3.x':
                - 'Youtube with C++': 'plugins/youtube/v3-cpp.md'
                - 'Youtube with Javascript': 'plugins/youtube/v3-js.md'
                - 'Youtube with Lua': 'plugins/youtube/v3-lua.md'
- Unity:
   - 'SDKBOX AllInOne': 'unity/allinone/index.md'
   - 'In-App Purchase': 'unity/iap/index.md'
   - 'Ratings & Reviews': 'unity/review/index.md'
   - 'SocialShare': 'unity/socialshare/index.md'
   - 'Google Analytics': 'unity/googleanalytics/index.md'
   - 'SDKBOX Play': 'unity/sdkboxplay/index.md'
- Unreal:
   - 'In-App Purchase': 'unreal/iap/index.md'
   - 'Chartboost': 'unreal/chartboost/index.md'
- LiveOps:
   - 'Setup': 'liveops/index.md'
   - 'Remote Configuration': 'liveops/remote-config.md'
   - 'Server-side IAP receipt verification': 'liveops/receipt-verification.md'
   - 'On-the-fly catalog management': 'liveops/catalog-management.md'
- Tutorials:
   - 'From Google to Amazon': 'qa/from-google-to-amazon.md'
   - 'Admob in Creator': 'qa/integration-admob-to-creator.md'
   - 'Fyber with Cocos2d-x': 'qa/integration-fyber-to-cocos.md'
   - 'Facebook with Cocos2d-x': 'qa/fb-share-on-cocos.md'
   - 'Fix Android 64K methods limit': 'qa/android_64k.md'
   - 'IAP with Unity': 'qa/integration-iap-on-unity.md'
   - 'GA with SDKBox GUI in Creator': 'qa/use-gui-integration-ga-to-creator.md'
   - 'Unity Custom Activity': 'qa/use-custom-activity-on-unity.md'
   - 'Encrypt Decrypt sdkbox_config.json': 'qa/crypt-sdkbox-config.md'
- About: 'release-note.md'

theme: mkdocs
theme_dir: 'theme'

google_analytics: ['UA-70044300-2', 'auto']
strict: true
markdown_extensions:
    - admonition
