site_name: SDKBOX
pages:
- Overview: 'index.md'
- Cocos:
    - 'Cocos Integration': 'cocos.md'
    - Installer: 'installer.md'
    - Plugins:
        - 'Achievements': 'plugins/achievement/index.md'
        - '_Achievements':
            - 'Cocos2d-x v3.x':
                - 'Achievements with C++': 'plugins/achievement/v3-cpp.md'
                - 'Achievements with Javascript': 'plugins/achievement/v3-js.md'
                - 'Achievements with Lua': 'plugins/achievement/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Achievements with C++': 'plugins/achievement/v2-cpp.md'
                - 'Achievements with Javascript': 'plugins/achievement/v2-js.md'
                - 'Achievements with Lua': 'plugins/achievement/v2-lua.md'
        - 'AdColony': 'plugins/adcolony/index.md'
        - '_AdColony':
            - 'Cocos2d-x v3.x':
                - 'AdColony with C++': 'plugins/adcolony/v3-cpp.md'
                - 'AdColony with JS': 'plugins/adcolony/v3-js.md'
                - 'AdColony with Lua': 'plugins/adcolony/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'AdColony with C++': 'plugins/adcolony/v2-cpp.md'
                - 'AdColony with Javascript': 'plugins/adcolony/v2-js.md'
                - 'AdColony with Lua': 'plugins/adcolony/v2-lua.md'
        - 'AdMob': 'plugins/admob/index.md'
        - '_AdMob':
            - 'Cocos2d-x v3.x':
                - 'AdMob with C++': 'plugins/admob/v3-cpp.md'
                - 'AdMob with Javascript': 'plugins/admob/v3-js.md'
                - 'AdMob with Lua': 'plugins/admob/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'AdMob with C++': 'plugins/admob/v2-cpp.md'
                - 'AdMob with Javascript': 'plugins/admob/v2-js.md'
                - 'AdMob with Lua': 'plugins/admob/v2-lua.md'
        - 'Ads': 'plugins/ads/index.md'
        - '_Ads':
            - 'Cocos2d-x v3.x':
                - 'Ads with C++': 'plugins/ads/v3-cpp.md'
                - 'Ads with Javascript': 'plugins/ads/v3-js.md'
                - 'Ads with Lua': 'plugins/ads/v3-lua.md'
        - 'AgeCheq': 'plugins/agecheq/index.md'
        - '_AgeCheq':
            - 'Cocos2d-x v3.x':
                - 'AgeCheq with C++': 'plugins/agecheq/v3-cpp.md'
                - 'AgeCheq with Javascript': 'plugins/agecheq/v3-js.md'
                - 'AgeCheq with Lua': 'plugins/agecheq/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'AgeCheq with C++': 'plugins/agecheq/v2-cpp.md'
                - 'AgeCheq with Javascript': 'plugins/agecheq/v2-js.md'
                - 'AgeCheq with Lua': 'plugins/agecheq/v2-lua.md'
        - 'Appodeal': 'plugins/appodeal/index.md'
        - '_Appodeal':
            - 'Cocos2d-x v3.x':
                - 'Appodeal with C++': 'plugins/appodeal/v3-cpp.md'
                - 'Appodeal with Javascript': 'plugins/appodeal/v3-js.md'
                - 'Appodeal with Lua': 'plugins/appodeal/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Appodeal with C++': 'plugins/appodeal/v2-cpp.md'
                - 'Appodeal with Javascript': 'plugins/appodeal/v2-js.md'
                - 'Appodeal with Lua': 'plugins/appodeal/v2-lua.md'
        - 'Bee7': 'plugins/bee7/index.md'
        - '_Bee7':
            - 'Cocos2d-x v3.x':
                - 'Bee7 with C++': 'plugins/bee7/v3-cpp.md'
                - 'Bee7 with Javascript': 'plugins/bee7/v3-js.md'
                - 'Bee7 with Lua': 'plugins/bee7/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Bee7 with C++': 'plugins/bee7/v2-cpp.md'
                - 'Bee7 with Javascript': 'plugins/bee7/v2-js.md'
                - 'Bee7 with Lua': 'plugins/bee7/v2-lua.md'
        - 'Chartboost': 'plugins/chartboost/index.md'
        - '_Chartboost':
            - 'Cocos2d-x v3.x':
                - 'Chartboost with C++': 'plugins/chartboost/v3-cpp.md'
                - 'Chartboost with Javascript': 'plugins/chartboost/v3-js.md'
                - 'Chartboost with Lua': 'plugins/chartboost/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Chartboost with C++': 'plugins/chartboost/v2-cpp.md'
                - 'Chartboost with Javascript': 'plugins/chartboost/v2-js.md'
                - 'Chartboost with Lua': 'plugins/chartboost/v2-lua.md'
        - 'Facebook': 'plugins/facebook/index.md'
        - '_Facebook':
            - 'Cocos2d-x v3.x':
                - 'Facebook with C++': 'plugins/facebook/v3-cpp.md'
                - 'Facebook with Javascript': 'plugins/facebook/v3-js.md'
                - 'Facebook with Lua': 'plugins/facebook/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Facebook with C++': 'plugins/facebook/v2-cpp.md'
                - 'Facebook with Javascript': 'plugins/facebook/v2-js.md'
                - 'Facebook with Lua': 'plugins/facebook/v2-lua.md'
        - 'Flurry Analytics': 'plugins/flurryanalytics/index.md'
        - '_Flurry Analytics':
            - 'Cocos2d-x v3.x':
                - 'Flurry with C++': 'plugins/flurryanalytics/v3-cpp.md'
                - 'Flurry with Javascript': 'plugins/flurryanalytics/v3-js.md'
                - 'Flurry with Lua': 'plugins/flurryanalytics/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Flurry with C++': 'plugins/flurryanalytics/v2-cpp.md'
                - 'Flurry with Javascript': 'plugins/flurryanalytics/v2-js.md'
                - 'Flurry with Lua': 'plugins/flurryanalytics/v2-lua.md'
        - 'Fyber': 'plugins/fyber/index.md'
        - '_Fyber':
            - 'Cocos2d-x v3.x':
                - 'Fyber with C++': 'plugins/fyber/v3-cpp.md'
                - 'Fyber with Javascript': 'plugins/fyber/v3-js.md'
                - 'Fyber with Lua': 'plugins/fyber/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Fyber with C++': 'plugins/fyber/v2-cpp.md'
                - 'Fyber with Javascript': 'plugins/fyber/v2-js.md'
                - 'Fyber with Lua': 'plugins/fyber/v2-lua.md'
        - 'Google Analytics': 'plugins/googleanalytics/index.md'
        - '_Google Analytics':
            - 'Cocos2d-x v3.x':
                - 'Google Analytics with C++': 'plugins/googleanalytics/v3-cpp.md'
                - 'Google Analytics with Javascript': 'plugins/googleanalytics/v3-js.md'
                - 'Google Analytics with Lua': 'plugins/googleanalytics/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Google Analytics with C++': 'plugins/googleanalytics/v2-cpp.md'
                - 'Google Analytics with Javascript': 'plugins/googleanalytics/v2-js.md'
                - 'Google Analytics with Lua': 'plugins/googleanalytics/v2-lua.md'
        - 'In-App Purchase': 'plugins/iap/index.md'
        - '_IAP':
            - 'Cocos2d-x v3.x':
                - 'In-App Purchases(IAP) with C++': 'plugins/iap/v3-cpp.md'
                - 'In-App Purchases(IAP) with Javascript': 'plugins/iap/v3-js.md'
                - 'In-App Purchases(IAP) with Lua': 'plugins/iap/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'In-App Purchases(IAP) with C++': 'plugins/iap/v2-cpp.md'
                - 'In-App Purchases(IAP) with Javascript': 'plugins/iap/v2-js.md'
                - 'In-App Purchases(IAP) with Lua': 'plugins/iap/v2-lua.md'
        - 'InMobi': 'plugins/inmobi/index.md'
        - '_InMobi':
            - 'Cocos2d-x v3.x':
                - 'InMobi with C++': 'plugins/inmobi/v3-cpp.md'
                - 'InMobi with Javascript': 'plugins/inmobi/v3-js.md'
                - 'InMobi with Lua': 'plugins/inmobi/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'InMobi with C++': 'plugins/inmobi/v2-cpp.md'
                - 'InMobi with Javascript': 'plugins/inmobi/v2-js.md'
                - 'InMobi with Lua': 'plugins/inmobi/v2-lua.md'
        - 'Kochava': 'plugins/kochava/index.md'
        - '_Kochava':
            - 'Cocos2d-x v3.x':
                - 'Kochava with C++': 'plugins/kochava/v3-cpp.md'
                - 'Kochava with Javascript': 'plugins/kochava/v3-js.md'
                - 'Kochava with Lua': 'plugins/kochava/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Kochava with C++': 'plugins/kochava/v2-cpp.md'
                - 'Kochava with Javascript': 'plugins/kochava/v2-js.md'
                - 'Kochava with Lua': 'plugins/kochava/v2-lua.md'
        - 'Leaderboard': 'plugins/leaderboard/index.md'
        - '_Leaderboard':
            - 'Cocos2d-x v3.x':
                - 'Leaderboard with C++': 'plugins/leaderboard/v3-cpp.md'
                - 'Leaderboard with Javascript': 'plugins/leaderboard/v3-js.md'
                - 'Leaderboard with Lua': 'plugins/leaderboard/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Leaderboard with C++': 'plugins/leaderboard/v2-cpp.md'
                - 'Leaderboard with Javascript': 'plugins/leaderboard/v2-js.md'
                - 'Leaderboard with Lua': 'plugins/leaderboard/v2-lua.md'
        - 'Playphone': 'plugins/playphone/index.md'
        - '_Playphone':
            - 'Cocos2d-x v3.x':
                - 'Playphone with C++': 'plugins/playphone/v3-cpp.md'
                - 'Playphone with Javascript': 'plugins/playphone/v3-js.md'
                - 'Playphone with Lua': 'plugins/playphone/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Playphone with C++': 'plugins/playphone/v2-cpp.md'
                - 'Playphone with Javascript': 'plugins/playphone/v2-js.md'
                - 'Playphone with Lua': 'plugins/playphone/v2-lua.md'
        - 'Ratings & Reviews': 'plugins/review/index.md'
        - '_Ratings & Reviews':
            - 'Cocos2d-x v3.x':
                - 'App Rating & Review with C++': 'plugins/review/v3-cpp.md'
                - 'App Rating & Review with Javascript': 'plugins/review/v3-js.md'
                - 'App Rating & Review with Lua': 'plugins/review/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'App Rating & Review with C++': 'plugins/review/v2-cpp.md'
                - 'App Rating & Review with Javascript': 'plugins/review/v2-js.md'
                - 'App Rating & Review with Lua': 'plugins/review/v2-lua.md'
        - 'SOOMLA Grow': 'plugins/soomlagrow/index.md'
        - '_SOOMLA Grow':
            - 'Cocos2d-x v3.x':
                - 'SOOMLA Grow with C++': 'plugins/soomlagrow/v3-cpp.md'
                - 'SOOMLA Grow with Javascript': 'plugins/soomlagrow/v3-js.md'
                - 'SOOMLA Grow with Lua': 'plugins/soomlagrow/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'SOOMLA Grow with C++': 'plugins/soomlagrow/v2-cpp.md'
                - 'SOOMLA Grow with Javascript': 'plugins/soomlagrow/v2-js.md'
                - 'SOOMLA Grow with Lua': 'plugins/soomlagrow/v2-lua.md'
        - 'Tune': 'plugins/tune/index.md'
        - '_Tune':
            - 'Cocos2d-x v3.x':
                - 'Tune with C++': 'plugins/tune/v3-cpp.md'
                - 'Tune with Javascript': 'plugins/tune/v3-js.md'
                - 'Tune with Lua': 'plugins/tune/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Tune with C++': 'plugins/tune/v2-cpp.md'
                - 'Tune with Javascript': 'plugins/tune/v2-js.md'
                - 'Tune with Lua': 'plugins/tune/v2-lua.md'
        - 'Valuepotion': 'plugins/valuepotion/index.md'
        - '_Valuepotion':
            - 'Cocos2d-x v3.x':
                - 'Valuepotion with C++': 'plugins/valuepotion/v3-cpp.md'
                - 'Valuepotion with Javascript': 'plugins/valuepotion/v3-js.md'
                - 'Valuepotion with Lua': 'plugins/valuepotion/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Valuepotion with C++': 'plugins/valuepotion/v2-cpp.md'
                - 'Valuepotion with Javascript': 'plugins/valuepotion/v2-js.md'
                - 'Valuepotion with Lua': 'plugins/valuepotion/v2-lua.md'
        - 'Vungle': 'plugins/vungle/index.md'
        - '_Vungle':
            - 'Cocos2d-x v3.x':
                - 'Vungle with C++': 'plugins/vungle/v3-cpp.md'
                - 'Vungle with Javascript': 'plugins/vungle/v3-js.md'
                - 'Vungle with Lua': 'plugins/vungle/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Vungle with C++': 'plugins/vungle/v2-cpp.md'
                - 'Vungle with Javascript': 'plugins/vungle/v2-js.md'
                - 'Vungle with Lua': 'plugins/vungle/v2-lua.md'
        - 'Youtube': 'plugins/youtube/index.md'
        - '_Youtube':
            - 'Cocos2d-x v3.x':
                - 'Youtube with C++': 'plugins/youtube/v3-cpp.md'
                - 'Youtube with Javascript': 'plugins/youtube/v3-js.md'
                - 'Youtube with Lua': 'plugins/youtube/v3-lua.md'
            - 'Cocos2d-x v2.x':
                - 'Youtube with C++': 'plugins/youtube/v2-cpp.md'
                - 'Youtube with Javascript': 'plugins/youtube/v2-js.md'
                - 'Youtube with Lua': 'plugins/youtube/v2-lua.md'
- Unity:
   - 'Unity Integration': 'unity/index.md'
   - Plugins:
       - 'In-App Purchase': 'unity/iap/index.md'
- Unreal:
   - 'Unreal Integration': 'unreal/index.md'
   - Plugins:
       - 'In-App Purchase': 'unreal/iap/index.md'
- LiveOps:
   - 'Setup': 'liveops/index.md'
   - 'Remote Config': 'liveops/remote-config.md'
   - 'Server-side IAP receipt verification': 'liveops/receipt-verification.md'
   - 'On-the-fly catalog management': 'liveops/catalog-management.md'
- About: 'release-note.md'

theme: mkdocs
theme_dir: 'theme'

google_analytics: ['UA-70044300-2', 'auto']

markdown_extensions:
    - admonition